title: Taha Berk Terekli
description: A data-driven engineer specializing in Data Science and Artificial Intelligence, focused on developing innovative automation systems and transforming data into actionable insights.
url: http://www.tahaberk.com
author: Taha Berk Terekli
lang: en
plugins:
  - jekyll-seo-tag
